# **Assignment 1**

In [1]:
import numpy as np
from collections import Counter

### Q1.

In [4]:
# (a)
arr = np.array([1,2,3,6,4,5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 6 3 2 1]


In [10]:
# (b)
array1 = np.array([[1,2,3],[2,4,5],[1,2,3]])
flat1 = array1.flatten()
print(flat1)

[1 2 3 2 4 5 1 2 3]


In [11]:
# (c)
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
comparision = np.array_equal(arr1,arr2)
print(comparision)

True


In [14]:
# (d)
def most_freq_info(x):
  vals,counts = np.unique(x,return_counts=True)
  most_freq = vals[np.argmax(counts)]
  indices = np.where(x == most_freq)[0]
  return most_freq,indices

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])
freq_x,idx_x = most_freq_info(x)
freq_y,idx_y = most_freq_info(y)
print(freq_x,idx_x)
print(freq_y,idx_y)

1 [0 5 7 8 9]
1 [0 1 2]


In [15]:
# (e)
gfg = np.matrix('[4,1,9;12,3,1;4,5,6]')
total_sum = np.sum(gfg)
row_sum = np.sum(gfg,axis=1)
col_sum = np.sum(gfg,axis=0)
print('Total Sum :',total_sum)
print('Row Sum :',row_sum)
print('Column Sum :',col_sum)

Total Sum : 45
Row Sum : [[14]
 [16]
 [15]]
Column Sum : [[20  9 16]]


In [16]:
# (f)
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])
diag_sum = np.trace(n_array)
eigen_values,eigen_vectors = np.linalg.eig(n_array)
inverse = np.linalg.inv(n_array)
det = np.linalg.det(n_array)
print('Diagonal Sum :',diag_sum)
print('Eigen Values :',eigen_values)
print('Eigen Vectors :',eigen_vectors)
print('Inverse :',inverse)
print('Determinant :',det)

Diagonal Sum : 176
Eigen Values : [98.16835147 28.097044   49.73460452]
Eigen Vectors : [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse : [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant : 137180.0000000001


In [18]:
# (g)
  # (i)
p1 = np.array([[1,2],[2,3]])
q1 = np.array([[4,5],[6,7]])
product1 = np.dot(p1,q1)
cov1 = np.cov(p1.T,q1.T)
print('Product :',product1)
print('Covarience :',cov1)

Product : [[16 19]
 [26 31]]
Covarience : [[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]


In [21]:
  # (ii)
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
product2 = np.dot(p2, q2)
cov2 = np.cov(p2.T, q2)
print('Product :',product2)
print('Covarience :',cov2)

Product : [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covarience : [[ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [-2.66666667 -2.66666667  4.33333333  5.5       ]
 [-3.5        -3.5         5.5         7.        ]]


In [23]:
# (h)
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner = np.inner(x, y)
outer = np.outer(x.flatten(), y.flatten())
cartesian = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)
print('Inner :',inner)
print('Outer :',outer)
print('Cartesian :',cartesian)

Inner : [[17 52]
 [13 62]]
Outer : [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian : [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


### Q2.

In [24]:
# (a)
  # (i)
array = np.array([[1, -2, 3],[-4, 5, -6]])
abs_array = np.abs(array)
print(abs_array)

[[ 1 -2  3]
 [-4  5 -6]]


In [27]:
  # (ii)
flat = array.flatten()
p_flat = np.percentile(flat, [25, 50, 75])
p_col = np.percentile(array, [25, 50, 75], axis=0)
p_row = np.percentile(array, [25, 50, 75], axis=1)
print('Percentile of Flattened array :',p_flat)
print('Percentile of each Column :',p_col)
print('Percentile of each row :',p_row)

Percentile of Flattened array : [-3.5 -0.5  2.5]
Percentile of each Column : [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentile of each row : [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [29]:
  # (iii)
mean_flat = np.mean(flat)
median_flat = np.median(flat)
std_flat = np.std(flat)
print('Mean of Flattened array :',mean_flat)
print('Median of Flattened array :',median_flat)
print('Standard Deviation of Flattened array :',std_flat)
print()

mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)
print('Mean of each Column :',mean_col)
print('Median of each Column :',median_col)
print('Standard Deviation of each Column :',std_col)
print()

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)
print('Mean of each row :',mean_row)
print('Median of each row :',median_row)
print('Standard Deviation of each row :',std_row)

Mean of Flattened array : -0.5
Median of Flattened array : -0.5
Standard Deviation of Flattened array : 3.8622100754188224

Mean of each Column : [-1.5  1.5 -1.5]
Median of each Column : [-1.5  1.5 -1.5]
Standard Deviation of each Column : [2.5 3.5 4.5]

Mean of each row : [ 0.66666667 -1.66666667]
Median of each row : [ 1. -4.]
Standard Deviation of each row : [2.05480467 4.78423336]


In [30]:
# (b)
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor_vals = np.floor(a)
ceil_vals = np.ceil(a)
trunc_vals = np.trunc(a)
rounded_vals = np.round(a)
print('Floor Values :',floor_vals)
print('Ceil Values :',ceil_vals)
print('Trunc Values :',trunc_vals)
print('Rounded Values :',rounded_vals)

Floor Values : [-2. -2. -1.  0.  1.  1.  3.]
Ceil Values : [-1. -1. -0.  1.  2.  2.  3.]
Trunc Values : [-1. -1. -0.  0.  1.  1.  3.]
Rounded Values : [-2. -2. -0.  0.  2.  2.  3.]


### Q3.

In [31]:
# (a)
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
sorted_indices = np.argsort(array)
smallest_4 = np.sort(array)[:4]
largest_5 = np.sort(array)[-5:]
print('Sorted Array :',sorted_array)
print('Sorted Indices :',sorted_indices)
print('Smallest 4 :',smallest_4)
print('Largest 5 :',largest_5)

Sorted Array : [ 10  16  16  52  54  62 453]
Sorted Indices : [0 3 4 1 5 2 6]
Smallest 4 : [10 16 16 52]
Largest 5 : [ 16  52  54  62 453]


In [32]:
# (b)
array2 = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integers = array2[array2 == array2.astype(int)]
floats = array2[array2 != array2.astype(int)]
print('Integers :',integers)
print('Floats :',floats)

Integers : [1. 2. 3. 2.]
Floats : [1.2 2.2]


### Q4.

In [39]:
# (a)
from PIL import Image
import numpy as np

# Create a 100x100 grayscale image with gradient
gray_image = np.tile(np.arange(100, dtype=np.uint8), (100, 1))

# Save image
Image.fromarray(gray_image).save("sample_grayscale.png")
print("Saved grayscale image as sample_grayscale.png")

def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)

    if len(arr.shape) == 2:
        # Grayscale
        np.savetxt("grayscale_image.txt", arr, fmt='%d')
        print("Saved: grayscale_image.txt")
    else:
        # RGB
        shape = arr.shape
        np.savetxt("rgb_image.txt", arr.reshape(-1, 3), fmt='%d')
        with open("rgb_shape.txt", "w") as f:
            f.write(f"{shape[0]} {shape[1]}")
        print("Saved: rgb_image.txt and rgb_shape.txt")
img_to_array("sample_grayscale.png")


# Create a 50x50 RGB image (random colors)
rgb_image = np.random.randint(0, 256, (50, 50, 3), dtype=np.uint8)
Image.fromarray(rgb_image).save("sample_rgb.png")
print("Saved RGB image as sample_rgb.png")

# Run function
img_to_array("sample_rgb.png")

# Load RGB image from text
with open("rgb_shape.txt", "r") as f:
    h, w = map(int, f.read().split())

rgb_flat = np.loadtxt("rgb_image.txt", dtype=int)

Saved grayscale image as sample_grayscale.png
Saved: grayscale_image.txt
Saved RGB image as sample_rgb.png
Saved: rgb_image.txt and rgb_shape.txt


In [40]:
# (b)
# For grayscale
gray_loaded = np.loadtxt("grayscale_image.txt", dtype=int)
print("Loaded grayscale array shape:", gray_loaded.shape)

# For RGB (assuming shape known or previously stored)
rgb_loaded = rgb_flat.reshape((h, w, 3))
print("Loaded RGB array shape:", rgb_loaded.shape)


Loaded grayscale array shape: (100, 100)
Loaded RGB array shape: (50, 50, 3)
